Repository TeeWhyKay/ChompFood, pull requests merged in 2021-09, with the labels that each got.

#1 added pull request template
  .github/pull_request_template.md
Labels: enhancement

#4 created restaurant model with name validation
  app/models/restaurant.rb
  db/migrate/20210914072452_create_restaurants.rb
  db/schema.rb
  test/models/restaurant_test.rb
Labels: enhancement, migration needed

#5 added restaurant table to schema
  db/migrate/20210914094726_create_restaurants_again.rb
  db/schema.rb
Labels: enhancement, migration needed

#6 added association between food and restaurant
  app/models/food.rb
  db/migrate/20210914100702_add_restaurant_reference_to_food.rb
  db/schema.rb
Labels: migration needed

#8 created order,food_order and migrations
  app/models/food.rb
  app/models/food_order.rb
  app/models/order.rb
  db/migrate/20210914101346_create_orders.rb
  db/migrate/20210914101807_create_food_orders.rb
  db/schema.rb
  test/models/food_order_test.rb
  test/models/order_test.rb
Labels: migration needed

#11 seeded db with restaurants
  Gemfile
  Gemfile.lock
  db/seeds.rb
Labels: seeding needed

#13 Feat add geocoder
  Gemfile
  Gemfile.lock
  app/models/restaurant.rb
  config/initializers/geocoder.rb
  db/migrate/20210915044359_add_coordinates_to_restaurants.rb
  db/migrate/20210915044729_add_address_to_resto.rb
  db/migrate/20210915062702_remove_long_lat_from_restaurants.rb
  db/schema.rb
  db/seeds.rb
Labels: migration needed, seeding needed

#14 Hotfix seed for restaurant
  app/models/restaurant.rb
  db/seeds.rb
Labels: seeding needed

#18 Routes restaurant
  app/assets/stylesheets/pages/_index.scss
  app/assets/stylesheets/pages/_restaurant.scss
  app/controllers/restaurants_controller.rb
  app/views/pages/home.html.erb
  app/views/restaurants/_restaurant.html.erb
  app/views/restaurants/index.html.erb
  app/views/restaurants/show.html.erb
  config/routes.rb
  test/controllers/restaurants_controller_test.rb
Labels: enhancement

#21 Feature: search restaurants near me
  Gemfile
  Gemfile.lock
  app/controllers/restaurants_controller.rb
  app/models/restaurant.rb
  app/views/restaurants/index.html.erb
  config/webpack/environment.js
  package.json
  yarn.lock
Labels: enhancement, bundle install

#29 reimplemented search
  app/controllers/restaurants_controller.rb
  config/environments/development.rb
Labels: enhancement

#33 Feat btn user location
  app/assets/stylesheets/pages/_form.scss
  app/assets/stylesheets/pages/_index.scss
  app/controllers/restaurants_controller.rb
  app/javascript/packs/application.js
  app/javascript/plugins/init_location.js
  app/views/pages/home.html.erb
Labels: enhancement

#34 Feat completable cart
  app/assets/stylesheets/pages/_food-orders.scss
  app/assets/stylesheets/pages/_index.scss
  app/controllers/food_orders_controller.rb
  app/controllers/orders_controller.rb
  app/javascript/packs/application.js
  app/javascript/plugins/init_cart.js
  app/views/food_orders/show.html.erb
  app/views/orders/create.html.erb
  app/views/orders/success.html.erb
  app/views/shared/_navbar.html.erb
  config/routes.rb
  test/controllers/orders_controller_test.rb
Labels: enhancement

#48 Fix/cart not showing until refresh bug
  .gitignore
  app/assets/stylesheets/pages/_food-orders.scss
  app/assets/stylesheets/pages/_index.scss
  app/assets/stylesheets/pages/_success.scss
  app/controllers/food_orders_controller.rb
  app/javascript/plugins/init_cart.js
  app/javascript/plugins/init_modal.js
  app/views/food_orders/_create_order.html.erb
  app/views/food_orders/index.html.erb
  app/views/food_orders/show.html.erb
  app/views/foods/_food.html.erb
  app/views/orders/success.html.erb
  app/views/shared/_navbar.html.erb
  config/routes.rb
Labels: help wanted

#49 Fix/hide orders with zero items
  app/javascript/plugins/init_modal.js
Labels: bug

#52 removed conflicting dependencies
  package.json
  yarn.lock
Labels: bundle install, yarn install

#53 Feat home search form
  app/assets/stylesheets/components/_banner.scss
  app/assets/stylesheets/pages/_form.scss
  app/views/pages/home.html.erb
Labels: enhancement

#59 updated seed to add 5 food items to each restaurant
  db/seeds.rb
Labels: seeding needed

#62 Hotfix location bug
  app/controllers/restaurants_controller.rb
Labels: bug

#65 Buttons
  app/assets/stylesheets/components/_navbar.scss
  app/views/shared/_navbar.html.erb
Labels: enhancement

#66 hotfix login
  app/views/shared/_navbar.html.erb
  config/routes.rb
Labels: bug
